{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretName" . }}
type: Opaque
data:
  {{- range .Values.env.secret }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}  
{{- end }}